### PR TITLE
ci: use npm audit

### PR DESCRIPTION
**Pull request by DanielRuf**
This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

nsp was shutdown in 2018 and we have `yarn / npm audit` now.

See https://blog.npmjs.org/post/175511531085/the-node-security-platform-service-is-shutting and https://github.com/nodesecurity/nsp

### CODE REVIEW

**Comment by pi0** [comment]
Can we use yar

**Comment by DanielRuf** [comment]
Most users still use npm so it makes not much sense to change it in package.json.
If you want to use Yarn for CI, it might be better than npm in some cases.

But I see no reasons why we should change to Yarn here.

**Comment by DanielRuf** [comment]
Also keep in mind that lockfiles are not used when people install a package (https://github.com/nuxt/webpackbar).

If you think Yarn is better suited here then we should prepare this accordingly (scripts and CI including caches).

**Comment by pi0** [comment]
@DanielRuf Yes. Because we have `yarn.lock` in the repository. People after installing a dependency don't run scripts from `node_modules/[...]/package.json`. This script is used for our CI which is using yarn :)

**Comment by DanielRuf** [comment]
Still, you do not want to use lockfiles as these are not affecting the install of the consumers.

And better let try if Yarn makes sense here in another PR and after asking the other maintainers and collaborators.

**Comment by DanielRuf** [comment]
Because if we do so we have to check all CI configs and the scripts and probably other references.

**Comment by pi0** [comment]
@DanielRuf 

- CircleCI is already using **yarn**
- `yarn.lock` is **not** published on NPM package. It is for repository only.

**Comment by pi0** [comment]
@DanielRuf I've implemented all changes to use yarn. 

I really appreciate your help and hope don't consider it as rudeness of me. 

Thanks again for your heads up and help :heart:

**Comment by pi0** [comment]
> keep in mind that you have to always update the lock file otherwise we can not reproduce the state on the users side 

We use renovate bot. But seems stopped working for this repo

**Pull request closed without merging**
