### PR TITLE
fix: Remove lodash and replace table

### PR DESCRIPTION
**Pull request by timneutkens**
Follow-up of https://github.com/nuxt/consola/pull/20

`lodash` has a 1.1MB install size and is 60% of webpackbar according to bundlephobia and packagephobia:

- Install size: https://packagephobia.now.sh/result?p=lodash
- Bundle size: https://bundlephobia.com/result?p=webpackbar@2.6.3

Regarding replacing the `table` dependency:

table is 29.2KB based on bundlephobia.com/result?p=table@4.0.3 it also has a 3MB install size and has a dependency on lodash.

text-table has no dependencies and is 11KB in total.

The goal of the PR is just to replace lodash, maybe some of these functions can be removed alltogether

### CODE REVIEW

**Comment by timneutkens** [comment]
It seems like there's only a check on Windows 🤔

**Comment by pi0** [comment]
Hi. Thanks for this PR. I really appreciate your help.

Regarding `lodash`, things are more complicated than just checking this plugin against bundlephobia.

Most of the users are using this package alongside with other dependencies that depend on `lodash` but may not depend on `lodash.*` dependencies. So at usual cases we are reusing `lodash` and i think it would be better to use that dependency.

**Comment by pi0** [comment]
@timneutkens Really thanks for your contribution. I've removed lodash dependency (at all) and replaced `table` with `text-table` as you suggested. WP2 is coming soon :)

**Comment by timneutkens** [comment]
:100:

**Pull request closed without merging**
